#!/usr/bin/env node
/**
 * scripts/verifyArgs_topAtlas.js
 *
 * Generates a Hardhat constructor-args file for verifying TopAtlas on Etherscan.
 *
 * It reads:
 *   out_top/deploy_<network>.json
 * and writes:
 *   out_top/verifyArgs_TopAtlas_<network>.js
 *
 * Usage:
 *   node scripts/verifyArgs_topAtlas.js --network sepolia
 *   node scripts/verifyArgs_topAtlas.js --network localhost
 */

const fs = require("fs");
const path = require("path");

function getArg(flag) {
  const idx = process.argv.indexOf(flag);
  if (idx === -1) return null;
  return process.argv[idx + 1] ?? null;
}

function main() {
  const network = getArg("--network") || "sepolia"; // default to sepolia since that's what you want to verify
  const outDir = "out_top";

  const deployPath = path.join(outDir, `deploy_${network}.json`);
  if (!fs.existsSync(deployPath)) {
    throw new Error(`Missing ${deployPath}. Deploy first.`);
  }

  const deploy = JSON.parse(fs.readFileSync(deployPath, "utf8"));
  const atlas = deploy.atlas;
  const items = deploy.items;

  if (!atlas || typeof atlas !== "string") {
    throw new Error(`deploy file missing "atlas" address: ${deployPath}`);
  }
  if (!Array.isArray(items) || items.length === 0) {
    throw new Error(`deploy file missing "items[]" array: ${deployPath}`);
  }

  // TopAtlas constructor args:
  // constructor(address[] memory ptrs, string[] memory names)
  const ptrs = [];
  const names = [];

  for (const it of items) {
    if (!it.pointer || typeof it.pointer !== "string") {
      throw new Error(`Bad/missing pointer for item: ${JSON.stringify(it)}`);
    }
    if (!it.name || typeof it.name !== "string") {
      throw new Error(`Bad/missing name for item: ${JSON.stringify(it)}`);
    }
    ptrs.push(it.pointer);
    names.push(it.name);
  }

  const argsFile = path.join(outDir, `verifyArgs_TopAtlas_${network}.js`);

  const content =
`// AUTO-GENERATED by scripts/verifyArgs_topAtlas.js
// network=${network}
// atlas=${atlas}
// date=${new Date().toISOString()}

module.exports = [
  ${JSON.stringify(ptrs, null, 2)},
  ${JSON.stringify(names, null, 2)},
];
`;

  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(argsFile, content);

  console.log("✅ Wrote constructor args file:");
  console.log(`   ${argsFile}`);
  console.log("");

  console.log("TopAtlas address:");
  console.log(`   ${atlas}`);
  console.log("");

  console.log("Run this to verify TopAtlas on Etherscan:");
  console.log(
    `npx hardhat verify --network ${network} ${atlas} --constructor-args ${argsFile}`
  );
  console.log("");

  console.log("Notes:");
  console.log("- This verifies TopAtlas only (recommended).");
  console.log("- Verifying each TopData contract is possible but noisy because each constructor arg is the full SVG bytes.");
}

main();